server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_ENDPOINT:-http://loki:3100/loki/api/v1/push}

scrape_configs:
  - job_name: container-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          environment: production
          __path__: /var/lib/docker/containers/*/*-json.log

  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          environment: production
          __path__: /var/log/nginx/access.log

  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          environment: production
          __path__: /var/log/nginx/error.log

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          environment: production
          __path__: /var/log/**/*.log
