sonar.projectKey=personalia-jkt
sonar.projectName=Personalia JKT
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/tests
sonar.test.inclusions=backend/tests/**/*.test.ts,backend/src/**/*.test.ts,frontend/tests/**/*.test.js
sonar.exclusions=backend/swagger-ui/**,backend/dist/**,frontend/dist/**,coverage/**,node_modules/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.typescript.tsconfigPaths=backend/tsconfig.json,frontend/tsconfig.json
sonar.coverage.exclusions=backend/src/app.ts,backend/src/server.ts,backend/src/migrations/**,frontend/src/config/main.jsx
