import { QueryTypes } from 'sequelize';

import type { Migration } from '../types/migration';

const TABLE_NAME = 'prs_master_setempat';
const LEGACY_TABLE_NAME = 'prs_master_setempat__uuid_old';

const migration: Migration = {
  async up({ queryInterface, sequelize, transaction }) {
    const exists = await queryInterface.tableExists(TABLE_NAME, {
      transaction,
    });
    if (!exists) return;

    const columns = await queryInterface.describeTable(TABLE_NAME);
    const idColumn = columns.id as { type?: unknown; defaultValue?: unknown } | undefined;
    if (!idColumn) return;

    const idTypeText = (idColumn.type == null ? '' : String(idColumn.type)).toLowerCase();
    const isIntLike =
      idTypeText.includes('int') || idTypeText.includes('integer') || idTypeText.includes('bigint') || idTypeText.includes('smallint');

    // If the id column isn't an integer type, we can't safely convert it to an identity column.
    // Usually this means the table was created earlier with UUID id. In that case:
    // - if there are no external FKs referencing it: recreate and copy data (UUID ids will be replaced)
    // - if there are external FKs: abort with a clear message (manual migration needed)
    if (!isIntLike) {
      // If referenced by other tables, recreating would break those relations.
      const referencingFks = await sequelize.query<{ conname: string }>(
        `
          SELECT c.conname
          FROM pg_constraint c
          JOIN pg_class t ON t.oid = c.confrelid
          WHERE c.contype = 'f' AND t.relname = :tableName
        `,
        {
          type: QueryTypes.SELECT,
          transaction,
          replacements: { tableName: TABLE_NAME },
        }
      );

      if (referencingFks.length > 0) {
        throw new Error(
          `Tabel "${TABLE_NAME}" memiliki kolom id bertipe "${String(
            idColumn.type
          )}" dan sedang direferensikan oleh foreign key (${referencingFks
            .map(r => r.conname)
            .join(', ')}). ` +
            `Tidak aman untuk recreate otomatis. Silakan migrasi manual (ubah FK/PK) atau drop relasi terkait terlebih dahulu.`
        );
      }

      const rows = await sequelize.query<{ exists: number }>(
        `SELECT 1 as exists FROM "${TABLE_NAME}" LIMIT 1`,
        { type: QueryTypes.SELECT, transaction }
      );

      const hasData = rows.length > 0;

      // Recreate table with INTEGER identity and (optionally) copy data.
      // NOTE: UUID ids will be replaced with new integer ids.
      await sequelize.query(
        `ALTER TABLE "${TABLE_NAME}" RENAME TO "${LEGACY_TABLE_NAME}"`,
        { transaction }
      );

      await sequelize.query(
        `
          CREATE TABLE "${TABLE_NAME}" (
            "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "kota_setempat" varchar(255) NOT NULL,
            "created_at" timestamp,
            "updated_at" timestamp,
            "deleted_at" timestamp
          )
        `,
        { transaction }
      );

      if (hasData) {
        await sequelize.query(
          `
            INSERT INTO "${TABLE_NAME}" ("kota_setempat", "created_at", "updated_at", "deleted_at")
            SELECT "kota_setempat", "created_at", "updated_at", "deleted_at"
            FROM "${LEGACY_TABLE_NAME}"
            ORDER BY "created_at" NULLS LAST, "kota_setempat" ASC
          `,
          { transaction }
        );
      }

      await sequelize.query(`DROP TABLE "${LEGACY_TABLE_NAME}"`, {
        transaction,
      });

      return;
    }

    const defaultValue = idColumn.defaultValue;
    const defaultValueText =
      defaultValue == null ? '' : String(defaultValue).toLowerCase();

    // If it's already using a sequence/identity, nothing to do.
    if (
      defaultValueText.includes('nextval') ||
      defaultValueText.includes('generated')
    ) {
      return;
    }

    // Ensure id is auto-increment for Postgres.
    await sequelize.query(
      'ALTER TABLE "prs_master_setempat" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY',
      { transaction }
    );
  },

  async down({ queryInterface, sequelize, transaction }) {
    const exists = await queryInterface.tableExists(TABLE_NAME, {
      transaction,
    });
    if (!exists) return;

    // Remove identity if it exists (best-effort).
    await sequelize.query(
      'ALTER TABLE "prs_master_setempat" ALTER COLUMN "id" DROP IDENTITY IF EXISTS',
      { transaction }
    );
  },
};

export default migration;
