server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.2.138:3100/loki/api/v1/push

scrape_configs:
  - job_name: personalia-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: nodejs
          env: development
          service: personalia-dev
          __path__: /var/log/**/*.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}'
      - timestamp:
          source: message
          format: '2006-01-02 15:04:05.000'
      - match:
          selector: '{job="personalia"}'
          stages:
            - regex:
                expression: '.*SQL QUERY.*'
            - labels:
                type: sql
      - match:
          selector: '{job="personalia"}'
          stages:
            - regex:
                expression: '.*SLOW SQL.*'
            - labels:
                type: sql_slow
