// Kontrak kolom tunggal untuk ekspor profil dan impor karyawan.
// `label` sengaja mengikuti bahasa pada halaman Profil Karyawan.
export const EMPLOYEE_EXCEL_COLUMNS = [
  { key: "nik", label: "ID Karyawan" },
  { key: "nama_lengkap", label: "Nama Lengkap" },
 
  { key: "kode_status_karyawan", label: "Status Karyawan" },
  { key: "status_aktif", label: "Status Aktif" },

  { key: "email_pribadi", label: "Email Pribadi" },
  { key: "no_ktp", label: "Nomor KTP" },
  { key: "no_pasport", label: "No Passport" },
  { key: "telp_pribadi", label: "Telepon Pribadi" },
  { key: "telp_kantor", label: "Telepon Kantor" },
  { key: "tipe_sekolah", label: "Tipe Sekolah" },
  { key: "id_master_setempat", label: "Kota Setempat" },
  { key: "tgl_join_penabur", label: "Tanggal Join PENABUR" },
  { key: "tgl_join_penabur_jkt", label: "Tanggal Join PENABUR Jakarta" },
  { key: "tgl_status_permanen", label: "Tanggal Status Tetap" },
  { key: "tgl_penuh_waktu", label: "Tanggal Penuh Waktu" },
  { key: "agama", label: "Agama" },
  { key: "status_nikah", label: "Status Nikah" },
  { key: "tanggal_pernikahan", label: "Tanggal Pernikahan" },
  { key: "alasan_berhenti_kerja", label: "Alasan Berhenti Kerja" },
  { key: "tanggal_inactive", label: "Tanggal Inactive" },
  { key: "tempat_lahir", label: "Tempat Lahir" },
  { key: "birth_date", label: "Tanggal Lahir" },
  { key: "gender", label: "Gender" },
  { key: "gol_darah", label: "Golongan Darah" },
  { key: "tinggi_badan", label: "Tinggi Badan" },
  { key: "berat_badan", label: "Berat Badan" },
  { key: "kewarganegaraan", label: "Kewarganegaraan" },
  { key: "npwp", label: "NPWP" },
  { key: "rekening", label: "Rekening" },
  { key: "kode_golongan", label: "Kode Golongan" },
  { key: "no_bpjs_kesehatan", label: "No BPJS Kesehatan" },
  { key: "no_bpjs_ketenagakerjaan", label: "No BPJS Ketenagakerjaan" },
  { key: "no_bpjs_danpes", label: "No BPJS Danpes" },
  { key: "nama_bpjs_danpes", label: "Nama BPJS Danpes" },
  { key: "etnis", label: "Etnis" },
  { key: "anggota_gereja", label: "Anggota Gereja" },
  { key: "instagram", label: "Instagram" },
  { key: "twitter", label: "Twitter" },
  { key: "no_kitas", label: "No KITAS" },
  { key: "no_visa", label: "No Visa" },
  { key: "no_tabita", label: "No TABITA" },
];

export const EMPLOYEE_EXCEL_HEADER_TO_KEY = Object.fromEntries(
  EMPLOYEE_EXCEL_COLUMNS.map(({ key, label }) => [label, key]),
);
